name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      JWT_PUBLIC_KEY:  ${{ secrets.JWT_PUBLIC_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Run integration tests
        run: make test-clean
